disable check for store dir

diff --git a/jobs/postgres/templates/postgres_ctl.erb b/jobs/postgres/templates/postgres_ctl.erb
--- a/jobs/postgres/templates/postgres_ctl.erb
+++ b/jobs/postgres/templates/postgres_ctl.erb
@@ -40,10 +40,10 @@ case "$1" in
 
     sysctl -w "kernel.shmmax=284934144"
 
-    if [ ! -d $STORE_DIR ]; then
-      echo "ERROR: storage directory doesn't exist"
-      echo "Please add persistent disk to this job"
-      exit 1
+#    if [ ! -d $STORE_DIR ]; then
+#      echo "ERROR: storage directory doesn't exist"
+#      echo "Please add persistent disk to this job"
+#      exit 1
     fi
 
     if [ ! -d $LOG_DIR ]; then
